name: Allure Report

on:
  workflow_run:
    workflows: ["CI - Automation Tests"]
    types:
      - completed

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish-allure-report:
    name: Publish Allure Report
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure Results
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          name: allure-results-all
          path: allure-results
          if_no_artifact_found: warn

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
